### ISSUE TITLE
启动容器报错

### ISSUE THREAD

**Issue by 1660962168** [captain686/Youth-Learning#20]
qndxx_1  |  * Starting periodic command scheduler cron                   [ OK ] 
qndxx_1  | Traceback (most recent call last):
qndxx_1  |   File "/home/dxx/app.py", line 14, in <module>
qndxx_1  |     from listen import bot
qndxx_1  |   File "/home/dxx/listen.py", line 5, in <module>
qndxx_1  |     from aiocqhttp import CQHttp, Message
qndxx_1  |   File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/__init__.py", line 19, in <module>
qndxx_1  |     from quart import Quart, request, abort, jsonify, websocket, Response
qndxx_1  |   File "/usr/local/lib/python3.9/dist-packages/quart/__init__.py", line 3, in <module>
qndxx_1  |     from jinja2 import escape, Markup
qndxx_1  | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
young-study_qndxx_1 exited with code 1

**Comment by captain686** [comment]
> qndxx_1 | * Starting periodic command scheduler cron [ OK ] qndxx_1 | Traceback (most recent call last): qndxx_1 | File "/home/dxx/app.py", line 14, in qndxx_1 | from listen import bot qndxx_1 | File "/home/dxx/listen.py", line 5, in qndxx_1 | from aiocqhttp import CQHttp, Message qndxx_1 | File "/usr/local/lib/python3.9/dist-packages/aiocqhttp/**init**.py", line 19, in qndxx_1 | from quart import Quart, request, abort, jsonify, websocket, Response qndxx_1 | File "/usr/local/lib/python3.9/dist-packages/quart/**init**.py", line 3, in qndxx_1 | from jinja2 import escape, Markup qndxx_1 | ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/**init**.py) young-study_qndxx_1 exited with code 1

已修复，重下下载源码将docker-compose up 替换为docker-compose --build运行

**Comment by captain686** [comment]
> > > qndxx_1 |* 启动周期性命令调度程序 cron [ 确定 ] qndxx_1 |回溯（最近一次调用）：qndxx_1 |文件"/home/dxx/app.py"，第 14 行，qndxx_1 |从侦听导入机器人qndxx_1 |文件"/home/dxx/listen.py"，第 5 行，qndxx_1 |从 aiocqhttp 导入 CQHttp，消息qndxx_1 |文件"/usr/local/lib/python3.9/dist-packages/aiocqhttp/**init**.py"，第 19 行，qndxx_1 |from quart import Quart， request， abort， jsonify， websocket， Response qndxx_1 |文件"/usr/local/lib/python3.9/dist-packages/quart/**init**.py"，第3行，qndxx_1 |从 jinja2 导入 escape， Markup qndxx_1 |ImportError：无法从 'jinja2' （/usr/local/lib/python3.9/dist-packages/jinja2/**init**.py） 导入名称 "escape" 时退出 study_qndxx_1，代码为 1
> > 
> > 
> > 已修复，重新下载源码将docker-compose up 替换为docker-compose --build运行
> 
> 好的 还有个问题就是在docker里面运行网页的标题会变成乱码 在本地python app.py的5000端口就不会乱码

这个问题是因为模板文件的编码导致，模板文件编码是按照微信端为准的

**Comment by captain686** [comment]
> > > qndxx_1 |* 启动周期性命令调度程序 cron [ 确定 ] qndxx_1 |回溯（最近一次调用）：qndxx_1 |文件"/home/dxx/app.py"，第 14 行，qndxx_1 |从侦听导入机器人qndxx_1 |文件"/home/dxx/listen.py"，第 5 行，qndxx_1 |从 aiocqhttp 导入 CQHttp，消息qndxx_1 |文件"/usr/local/lib/python3.9/dist-packages/aiocqhttp/**init**.py"，第 19 行，qndxx_1 |from quart import Quart， request， abort， jsonify， websocket， Response qndxx_1 |文件"/usr/local/lib/python3.9/dist-packages/quart/**init**.py"，第3行，qndxx_1 |从 jinja2 导入 escape， Markup qndxx_1 |ImportError：无法从 'jinja2' （/usr/local/lib/python3.9/dist-packages/jinja2/**init**.py） 导入名称 "escape" 时退出 study_qndxx_1，代码为 1
> > 
> > 
> > 已修复，重新下载源码将docker-compose up 替换为docker-compose --build运行
> 
> 好的 还有个问题就是在docker里面运行网页的标题会变成乱码 在本地python app.py的5000端口就不会乱码

抱歉之前看错了这个问题，现在已经修复了
